import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../../globals.css";
import { ThemeProvider } from "@/components/ThemeProvider/ThemeProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-gray dark:bg-bg_blue ${inter.className}`}>
        <Toaster position="top-center" />
        {children}
      </body>
    </html>
  );
}
