import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";
import SideBar from "@/components/SideBar/SideBar";
import Header from "@/components/Header/Header";
import { ThemeProvider } from "@/components/ThemeProvider/ThemeProvider";
import { AuthProvider } from "@/app/Provider";
// import AuthGuard from "../../../../AuthGuard";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-gray dark:bg-bg_blue ${inter.className}`}>
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* <AuthGuard> */}
            <div className="flex h-screen container">
              <SideBar />
              <div className="flex flex-col flex-1 h-screen">
                <Header />
                <main className="flex-1 sm:p-6 p-3 h-0 min-h-0 overflow-y-auto">
                  {children}
                </main>
              </div>
            </div>
            {/* </AuthGuard> */}
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
